PRESETS: list[dict] = [
    {
        "id": "classic_vhs",
        "name": "Classic Timestamp",
        "description": "Soft tape texture with a chunky lower-corner date stamp.",
        "category": "📼 VHS",
        "overlay_mode": "classic_timestamp",
        "effects": {
            "noise": 0.35,
            "scanlines": 0.25,
            "blur": 0.15,
            "contrast": 1.08,
            "saturation": 0.82,
            "brightness": -0.02,
            "sharpen": 0.12,
        },
    },
    {
        "id": "rec_camcorder",
        "name": "REC Camcorder UI",
        "description": "Red REC dot, corner brackets, SP marker, live counter, and date block.",
        "category": "📸 Cameras",
        "overlay_mode": "rec_camcorder",
        "effects": {
            "noise": 0.3,
            "scanlines": 0.18,
            "blur": 0.08,
            "contrast": 1.1,
            "saturation": 0.88,
            "brightness": -0.02,
            "sharpen": 0.2,
        },
    },
    {
        "id": "play_vhs_1985",
        "name": "PLAY VHS 1985",
        "description": "PLAY arrow, VHS label, date/time OSD, tracking bands, and white tape glitches.",
        "category": "📼 VHS",
        "overlay_mode": "play_vhs_1985",
        "effects": {
            "noise": 0.42,
            "scanlines": 0.32,
            "blur": 0.16,
            "contrast": 1.2,
            "saturation": 0.7,
            "brightness": -0.05,
            "sharpen": 0.12,
        },
    },
    {
        "id": "camera_source_iphone",
        "name": "CAMERA1 Source iPhone",
        "description": "Chunky CAMERA1 / SOURCE IPHONE OSD with playback counter, date footer, and soft CRT frame.",
        "category": "📸 Cameras",
        "overlay_mode": "camera_source_iphone",
        "effects": {
            "noise": 0.5,
            "scanlines": 0.3,
            "blur": 0.18,
            "contrast": 1.12,
            "saturation": 0.78,
            "brightness": -0.03,
            "sharpen": 0.1,
        },
    },
    {
        "id": "dirty_camcorder",
        "name": "Dirty Camcorder",
        "description": "Heavy static, REC overlay, SP marker, and rough tape interference.",
        "category": "📼 Horror",
        "overlay_mode": "dirty_camcorder",
        "effects": {
            "noise": 0.68,
            "scanlines": 0.48,
            "blur": 0.22,
            "contrast": 1.16,
            "saturation": 0.72,
            "brightness": -0.04,
            "sharpen": 0.08,
        },
    },
    {
        "id": "late_night_tv",
        "name": "Late Night TV",
        "description": "Dim taped-TV look with PLAY label, VHS OSD, tracking bars, and crushed color.",
        "category": "📺 CRT",
        "overlay_mode": "play_vhs_1985",
        "effects": {
            "noise": 0.28,
            "scanlines": 0.42,
            "blur": 0.1,
            "contrast": 1.24,
            "saturation": 0.68,
            "brightness": -0.08,
            "sharpen": 0.18,
        },
    },
    {
        "id": "retro_tape_glitch",
        "name": "Retro Tape Glitch",
        "description": "Aggressive tracking noise, white glitch chunks, and unstable analog contrast.",
        "category": "🌈 Experimental",
        "overlay_mode": "retro_tape_glitch",
        "effects": {
            "noise": 0.62,
            "scanlines": 0.34,
            "blur": 0.08,
            "contrast": 1.32,
            "saturation": 0.9,
            "brightness": -0.03,
            "sharpen": 0.28,
        },
    },
    {
        "id": "basement_tape_1994",
        "name": "Basement Tape 1994",
        "description": "Muted home-video VHS with low saturation, sleepy blur, and a grounded timestamp.",
        "category": "📼 VHS",
        "overlay_mode": "classic_timestamp",
        "effects": {
            "noise": 0.44,
            "scanlines": 0.28,
            "blur": 0.28,
            "contrast": 1.02,
            "saturation": 0.58,
            "brightness": -0.06,
            "sharpen": 0.06,
        },
    },
    {
        "id": "arcade_crt",
        "name": "Arcade CRT",
        "description": "Bright cabinet-screen punch with strong scanlines, glow, and saturated phosphor color.",
        "category": "📺 CRT",
        "overlay_mode": "classic_timestamp",
        "effects": {
            "noise": 0.2,
            "scanlines": 0.62,
            "blur": 0.06,
            "contrast": 1.35,
            "saturation": 1.42,
            "brightness": 0.02,
            "sharpen": 0.24,
        },
    },
    {
        "id": "crt_newsroom",
        "name": "CRT Newsroom",
        "description": "Broadcast monitor texture with crisp contrast, visible scanlines, and mild tape dirt.",
        "category": "📺 CRT",
        "overlay_mode": "play_vhs_1985",
        "effects": {
            "noise": 0.32,
            "scanlines": 0.5,
            "blur": 0.08,
            "contrast": 1.28,
            "saturation": 0.82,
            "brightness": -0.03,
            "sharpen": 0.22,
        },
    },
    {
        "id": "security_monitor",
        "name": "Security Monitor",
        "description": "Cold CCTV-style monitor with REC frame, hard contrast, and dry surveillance noise.",
        "category": "📺 CRT",
        "overlay_mode": "rec_camcorder",
        "effects": {
            "noise": 0.46,
            "scanlines": 0.44,
            "blur": 0.04,
            "contrast": 1.42,
            "saturation": 0.36,
            "brightness": -0.1,
            "sharpen": 0.18,
        },
    },
    {
        "id": "handycam_night",
        "name": "Handycam Night",
        "description": "Dark camcorder recording with REC UI, lifted shadows, and gritty low-light grain.",
        "category": "📸 Cameras",
        "overlay_mode": "rec_camcorder",
        "effects": {
            "noise": 0.58,
            "scanlines": 0.24,
            "blur": 0.16,
            "contrast": 1.18,
            "saturation": 0.52,
            "brightness": -0.12,
            "sharpen": 0.12,
        },
    },
    {
        "id": "mini_dv_trip",
        "name": "MiniDV Trip",
        "description": "Late-2000s camcorder playback with clean source labels and softened digital tape edges.",
        "category": "📸 Cameras",
        "overlay_mode": "camera_source_iphone",
        "effects": {
            "noise": 0.24,
            "scanlines": 0.18,
            "blur": 0.1,
            "contrast": 1.08,
            "saturation": 0.92,
            "brightness": -0.01,
            "sharpen": 0.14,
        },
    },
    {
        "id": "super8_home_movie",
        "name": "Super 8 Home Movie",
        "description": "Warm film-memory color with soft grain, gentle blur, and a nostalgic date stamp.",
        "category": "🎞 Film",
        "overlay_mode": "classic_timestamp",
        "effects": {
            "noise": 0.3,
            "scanlines": 0.08,
            "blur": 0.24,
            "contrast": 1.08,
            "saturation": 0.66,
            "brightness": 0.03,
            "sharpen": 0.04,
        },
    },
    {
        "id": "polaroid_fade",
        "name": "Polaroid Fade",
        "description": "Washed instant-photo palette with low contrast, soft edges, and faded highlights.",
        "category": "🎞 Film",
        "overlay_mode": "classic_timestamp",
        "effects": {
            "noise": 0.18,
            "scanlines": 0.02,
            "blur": 0.2,
            "contrast": 0.86,
            "saturation": 0.55,
            "brightness": 0.08,
            "sharpen": 0.02,
        },
    },
    {
        "id": "cinema_leader",
        "name": "Cinema Leader",
        "description": "Projected-film contrast with pronounced grain, subdued color, and old reel softness.",
        "category": "🎞 Film",
        "overlay_mode": "classic_timestamp",
        "effects": {
            "noise": 0.4,
            "scanlines": 0.06,
            "blur": 0.14,
            "contrast": 1.32,
            "saturation": 0.62,
            "brightness": -0.02,
            "sharpen": 0.08,
        },
    },
    {
        "id": "win95_capture",
        "name": "Windows 95 Capture",
        "description": "Retro PC screen grab with crunchy monitor scanlines and pale desktop-era color.",
        "category": "🖥 Retro PCs",
        "overlay_mode": "classic_timestamp",
        "effects": {
            "noise": 0.16,
            "scanlines": 0.52,
            "blur": 0.03,
            "contrast": 1.18,
            "saturation": 0.76,
            "brightness": 0.01,
            "sharpen": 0.34,
        },
    },
    {
        "id": "dos_terminal",
        "name": "DOS Terminal",
        "description": "Dark command-line monitor feel with greenish low saturation and sharp scanlines.",
        "category": "🖥 Retro PCs",
        "overlay_mode": "classic_timestamp",
        "effects": {
            "noise": 0.26,
            "scanlines": 0.66,
            "blur": 0.02,
            "contrast": 1.46,
            "saturation": 0.22,
            "brightness": -0.12,
            "sharpen": 0.28,
        },
    },
    {
        "id": "web_1_0_screenshot",
        "name": "Web 1.0 Screenshot",
        "description": "Early internet screenshot vibe with monitor sharpness, mild color crush, and scanlines.",
        "category": "🖥 Retro PCs",
        "overlay_mode": "classic_timestamp",
        "effects": {
            "noise": 0.12,
            "scanlines": 0.38,
            "blur": 0.01,
            "contrast": 1.22,
            "saturation": 1.08,
            "brightness": 0.0,
            "sharpen": 0.4,
        },
    },
    {
        "id": "found_footage_3am",
        "name": "Found Footage 3AM",
        "description": "Pitchy handheld horror tape with dirty REC UI, harsh noise, and crushed blacks.",
        "category": "📼 Horror",
        "overlay_mode": "dirty_camcorder",
        "effects": {
            "noise": 0.78,
            "scanlines": 0.5,
            "blur": 0.2,
            "contrast": 1.5,
            "saturation": 0.34,
            "brightness": -0.18,
            "sharpen": 0.05,
        },
    },
    {
        "id": "cursed_tape",
        "name": "Cursed Tape",
        "description": "Bleak haunted cassette texture with unstable tracking and ghostly gray color.",
        "category": "📼 Horror",
        "overlay_mode": "retro_tape_glitch",
        "effects": {
            "noise": 0.82,
            "scanlines": 0.58,
            "blur": 0.26,
            "contrast": 1.38,
            "saturation": 0.2,
            "brightness": -0.14,
            "sharpen": 0.02,
        },
    },
    {
        "id": "motel_tv",
        "name": "Motel TV",
        "description": "Bad late-night television glow with dirty scanlines, dim color, and PLAY overlay.",
        "category": "📼 Horror",
        "overlay_mode": "play_vhs_1985",
        "effects": {
            "noise": 0.55,
            "scanlines": 0.54,
            "blur": 0.18,
            "contrast": 1.2,
            "saturation": 0.48,
            "brightness": -0.11,
            "sharpen": 0.06,
        },
    },
    {
        "id": "datamosh_rainbow",
        "name": "Datamosh Rainbow",
        "description": "Color-shifted experimental tape look with bright saturation and glitch-heavy tracking.",
        "category": "🌈 Experimental",
        "overlay_mode": "retro_tape_glitch",
        "effects": {
            "noise": 0.5,
            "scanlines": 0.2,
            "blur": 0.03,
            "contrast": 1.4,
            "saturation": 1.65,
            "brightness": 0.02,
            "sharpen": 0.36,
        },
    },
    {
        "id": "acid_public_access",
        "name": "Acid Public Access",
        "description": "Oversaturated public-access TV energy with loud contrast and playful analog grit.",
        "category": "🌈 Experimental",
        "overlay_mode": "play_vhs_1985",
        "effects": {
            "noise": 0.42,
            "scanlines": 0.34,
            "blur": 0.05,
            "contrast": 1.55,
            "saturation": 1.82,
            "brightness": 0.04,
            "sharpen": 0.18,
        },
    },
    {
        "id": "laserdisc_dream",
        "name": "Laserdisc Dream",
        "description": "Glossy retro-future playback with clean OSD, neon color, and soft analog shimmer.",
        "category": "🌈 Experimental",
        "overlay_mode": "camera_source_iphone",
        "effects": {
            "noise": 0.22,
            "scanlines": 0.24,
            "blur": 0.08,
            "contrast": 1.22,
            "saturation": 1.36,
            "brightness": 0.03,
            "sharpen": 0.16,
        },
    },
]


def list_presets() -> list[dict]:
    return PRESETS


def get_preset(preset_id: str) -> dict | None:
    for preset in PRESETS:
        if preset["id"] == preset_id:
            return preset

    return None
